apiVersion: v1
kind: Secret
metadata:
  name: sql-edge-creds
type: Opaque
data:
  MSSQL_SA_PASSWORD: bXNzcWw4NzEu

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/mssql-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - instance-1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mssql-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-sql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-sql
  template:
    metadata:
      labels:
        app: azure-sql
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/worker"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: azure-sql
          image: mcr.microsoft.com/azure-sql-edge
          env:
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-edge-creds
                  key: MSSQL_SA_PASSWORD
            - name: ACCEPT_EULA
              value: "Y"
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/mssql/data
          ports:
            - containerPort: 1433
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: mssql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: azure-sql-service
spec:
  type: NodePort
  selector:
    app: azure-sql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 31200
