apiVersion: v1
kind: Secret
metadata:
  name: sql-edge-creds
type: Opaque
data:
  MSSQL_SA_PASSWORD: bXNzcWw4NzEu

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/mssql-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - instance-1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mssql-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-edge-deployment
spec:
  selector:
    matchLabels:
      app: sql-edge
  replicas: 1
  template:
    metadata:
      labels:
        app: sql-edge
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/worker"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: sql-edge
          image: mcr.microsoft.com/azure-sql-edge
          env:
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-edge-creds
                  key: MSSQL_SA_PASSWORD
            - name: ACCEPT_EULA
              value: "Y"
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: sql-edge-persistent-storage
              mountPath: /var/opt/mssql/data
          command: ["/opt/mssql/bin/sqlservr"]
      volumes:
        - name: sql-edge-persistent-storage
          persistentVolumeClaim:
            claimName: sql-edge-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: sql-edge-service
spec:
  type: NodePort
  selector:
    app: sql-edge
  ports:
    - name: sql-edge
      port: 1433
      targetPort: 1433
      nodePort: 31200
  clusterIP: "10.101.99.120"
