FROM mysql:8

# Set MySQL environment variables
ENV MYSQL_ROOT_PASSWORD=mysql871.
ENV MYSQL_DATABASE=cons
ENV MYSQL_USER=enerji
ENV MYSQL_PASSWORD=mysql871.

# Expose port 3306
EXPOSE 3306

# Start MySQL service
CMD ["mysqld"]
