FROM phpmyadmin/phpmyadmin

ENV PMA_HOST=10.101.99.126 \
    PMA_PORT=3306

EXPOSE 80

# Optionally, add a health check here

# If you need to use an imagePullSecret, uncomment the line below
# ADD my-registry-key /root/.docker/config.json
